// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Post struct {
	ID       int32  `json:"id"`
	PostID   string `json:"post_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category"`
}
